### ISSUE TITLE
Error: Authentication is required.

### ISSUE THREAD

**Issue by molinto** [vegasbrianc/docker-compose-demo#1]
sharry@sharry-Precision-T1700:~/Development/Projects/docker-compose-demo$ docker-compose up -d
Creating dockercomposedemo_redis_1...
Pulling image redis:latest...
Pulling repository docker.io/library/redis
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Authentication is required.

**Comment by vegasbrianc** [comment]
This seems like a docker error. I tested quickly on a new server and it works.

Can you verify you have the latest Docker version 1.8.1 and docker-compose versions(below)

```
root@Docker02:~/comp-test# docker -v
Docker version 1.8.1, build d12ea79

root@Docker02:~/comp-test# docker-compose version
docker-compose version: 1.4.0
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by molinto** [comment]
docker -v
Docker version 1.8.2, build 0a8c2e3

docker-compose --version
docker-compose 1.2.0

Did docker update command: curl -sSL https://get.docker.com/ | sh
But still the same values :(

**Comment by vegasbrianc** [comment]
Try updating docker-compose as well - https://docs.docker.com/compose/install/ Let me know if this solves it or not.

**Comment by molinto** [comment]
Thanks! Had to remove all existing containers, remove docker & update to the correct version.
Thanks for your help, my bad.
